name: Android CI

on:
  push

jobs:
  build:
    name: Test & Build
    runs-on: macos-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run Unit Tests
        if: ${{ !contains(github.ref, 'l10n_master') }}
        run: bash ./gradlew test

      - name: Accept Licenses
        if: ${{ !contains(github.ref, 'l10n_master') }}
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Run UI Tests
        if: ${{ !contains(github.ref, 'l10n_master') }}
        run: bash ./gradlew allDevicesFdroidDebugAndroidTest

      - name: Assemble App Debug APK
        run: ./gradlew assembleDebug

      - name: Upload App Play APK
        uses: actions/upload-artifact@v4
        with:
          name: app-play-debug
          path: app/build/outputs/apk/play/debug/app-play-debug.apk

      - name: Upload App F-Droid APK
        uses: actions/upload-artifact@v4
        with:
          name: app-fdroid-debug
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk