name: Android CI

on:
  push

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Unit Tests
        run: bash ./gradlew test -Pbase64EncodedPublicKey=${{secrets.PUBLIC_KEY}} --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Assemble App Debug APK
        run: ./gradlew assembleDebug -Pbase64EncodedPublicKey=${{secrets.PUBLIC_KEY}} --stacktrace

      - name: Upload App Play APK
        uses: actions/upload-artifact@v4
        with:
          name: app-play-debug
          path: app/build/outputs/apk/play/debug/app-play-debug.apk

      - name: Upload App F-Droid APK
        uses: actions/upload-artifact@v4
        with:
          name: app-fdroid-debug
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk