name: Provide Signed Release for F-Droid

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Master Branch
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Assemble Release
        run: ./gradlew clean assembleFdroidRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        id: sign_release
        with:
          releaseDirectory: app/build/outputs/apk/fdroid/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create Release on GitHub
        uses: ncipollo/release-action@v1
        with:
            artifacts: ${{ steps.sign_release.outputs.signedReleaseFile }}
            artifactErrorsFailBuild: true
            prerelease: false
            tag: '${{ github.ref_name}}-fdroid'
            commit: master