name: Master Build with UI Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble App Debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload App APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-${{github.run_number}}
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble Android Instrumentation Tests
        run: ./gradlew assembleDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest-${{github.run_number}}
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: Run UI Tests with Firebase Test Lab
    needs: apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download App APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-${{github.run_number}}

      - name: Download Android Test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest-${{github.run_number}}

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug-${{github.run_number}}/app-debug.apk --test app-debug-androidTest-${{github.run_number}}/app-debug-androidTest.apk --device model=Pixel2,version=29,locale=de,orientation=portrait
